# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'layabox' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for layabox
  pod 'Firebase/Core'
  pod 'Firebase/AdMob'

  target 'layaboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'layaboxUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
